### ISSUE TITLE
AJAX calls are unable to refresh cookies

### ISSUE THREAD

**Issue by dresdor** [mderriey/aspnet-core-token-renewal#2]
We have an interesting issue in two of our applications using this sample code for token renewal.

When we have an ajax call (either through a telerik table in one app or angular code in another) we call a local endpoint which is behind an authorize tag.  If our token is expired, we get a redirect (302) to login, which on redirect succeeds in a get (200).  Is there any way to refresh our cookies or force a browser refresh through the authenticate middleware?

**Comment by mderriey** [comment]
Hi there,

> If our token is expired, we get a redirect (302) to login, which on redirect succeeds in a get (200)

Please note that the automatic token (and cookie) renewal can only happen while the token is still valid.
This will happen if, at the time of the request, the cookie is found to have less than half its lifetime left.
I'm not entirely sure that sentence is clear, so let's say cookies have a 1-minute lifetime, they will be renewed along with the access token if they are to expire in 30 seconds or less.

> Is there any way to refresh our cookies or force a browser refresh through the authenticate middleware?

Now if I understand correctly, your problem is the following:

 - the cookie expires without getting the chance to be renewed
 - once expired, you make an AJAX request that needs to be authenticated
 - as the cookie is expired, the web application redirects the request to IdentityServer so that the user can login again, but this fails

Is that correct?

**Comment by dresdor** [comment]
the flow for a non-ajax version of our application based on my understanding would be:

* user logs in, this sets a cookie for the identity server application
* user is redirected to the client app which sets a cookie based on the duration of the access token
* normally, when a request is made with a valid access token with less than half their lifetime, it will renew the token and client cookie.
* If token/cookie is expired, the browser will redirect to the identity server app, which sees it has a cookie for the user, and reauthorizes them and redirects them (step 2).  

The issue is with an Ajax call, the main browser cannot be redirected to the identity server app, where the step 4 magic happens.

**Comment by mderriey** [comment]
OK, I'm glad we're on the same page.

I guess the solution depends on how you make your AJAX call:

 - if they use `XMLHttpRequest`, then the redirects are automatically followed, and there's not much you can do here;
 - if they use the new `fetch` API, the [`redirect` parameter](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters) allows to specify the behaviour when the response is a redirect. Valid values are `follow`, `error` or `manual`. The default is `follow`, and in your case, you might want to play with `manual` so you can handle them and refresh the page or redirect the user directly to IdentityServer

Going back to `XMLHttpRequest`, since redirects are automatically followed, we need to come up with a way that prevents the server from issuing a redirect.

I've put together something in the [`handle-unauthenticated-ajax-calls`](https://github.com/mderriey/TokenRenewal/tree/feature/handle-unauthenticated-ajax-calls) branch; you can see the comparison with the `master` branch by using [this link](https://github.com/mderriey/TokenRenewal/compare/feature/handle-unauthenticated-ajax-calls)

On the `Home/About` page, there's a new button that makes an AJAX call that returns the claims of the logged-in user; while you're logged in, this works fine and returns the claims. If the cookie is about to expire, the automatic renewal of the cookie happens, like when a full refresh of the page is done.

If you're not logged in, though, we hook into the OIDC middleware using the `OnRedirectToIdentityProvider` event which is fired right before the redirect is sent back to the browser. In this event, if we find that the request is an AJAX one, we prevent the redirect from happening and send a 401 back to the browser. On the JS side, the 401 is handled and currently displays a popup to the user. In your case, so it's less intrusive, you could automatically refresh the page or come up with something better.

A quick note: I didn't spend much time on this, and I find the implementation a bit hacky. Please adapt to your needs and make sure it fits the bill.

**Comment by dresdor** [comment]
Thanks, I will look into this when I am back in the office on Monday.

In one of the applications with this issue, it's an Angular service call
that is triggering it, and in the other it is a Telerik ajax call, so I'm
not sure off hand what those look like under the hood.  We did a semi-hacky
workaround with an Http Interceptor in the angular side and are ignoring
the telerik side because it's in a pure MVC app instead of a single page
angular app, so full page refreshes happen more regularly.

**Comment by mderriey** [comment]
Closing this as it's been a while. Please reopen if needed.
