### ISSUE TITLE
IE 11 and Edge failing to load

### ISSUE THREAD

**Issue by dresdor** [mderriey/aspnet-core-token-renewal#25]
I'm experiencing a very weird issue in our redirects with Microsoft's browsers.

We have two web applications secured behind an identity server 4 implementation.  One of these applications (Sales App) is an angular 5 app with a very basic MVC application serving it up, and the other (Admin App) is a fully fledged MVC application.  

When we try to load SalesAppUrl it redirects to our identity portal, as I'd expect, and allows us to login.  After the redirect, though, Edge and IE both give the error INET_E_DOWNLOAD_FAILURE, and look like they did not even try to load the page (from network traffic).   The redirect from the identity server occur, but all other calls stay stuck at "pending" with a 0s time.  The only console information is navigation occured and "CSS3121: The media query -ms-viewport has been deprecated."

The real weird thing is that when we try to go to AdminAppUrl, it does the same thing for Edge, but actually loads fully in IE 11 without issue.

When I run the SalesApp locally, connected to the same identity server as the live version, everything works fine.

Our middleware configuration is in [this SO question](https://stackoverflow.com/questions/55170698/identity-server-4-authorized-app-not-working-in-ie-11-or-edge)

I am working at creating a minimally functional version of this to show the issue (though it's a challenge due to the fact that local code works fine).

Versions:
Microsoft Edge 41.16299.967.0
Microsoft EdgeHTML 16.16299
Internet Explorer 11.0.110
IdentityServer4.AspNetIdentity (2.3.0)
IdentityServer4.Entity.Framework(2.3.2)
.Net Core 2.1

It's been suggested that it might be CSRF.  Have you seen anything like this?  We are using this token renewal process.

**Comment by mderriey** [comment]
Hi there 👋

Thanks for reaching out.
I'm not too sure, but something bugs me with the screenshots you posted on Stack Overflow.

![image](https://user-images.githubusercontent.com/6102639/55265914-728b8e80-52ce-11e9-9b9b-a562b39e4115.png)

Here's my understanding of what happens, section by section:

1. you try to access your Sales app;
1. because you're not authenticated, this app responds with an authorization request to your Identity Server instance, passing the `client_id`, `redirect_uri` and other parameters;
1. Identity Server validates this request, finds it's legit, so it shows you the login page, and loads the associated resources;
1. you enter your credentials and submit the form back to Identity Server;
1. the credentials are found to be correct, so Identity Server serves an HTML page which contains a `<form>` pointing back to the Sales app;
1. some JS code in the previous page automatically POSTs the `<form>` element; at this stage the OIDC middleware of the Sales app should get what it needs to transform the claims into a `ClaimsIdentity` and authenticate you by creating a cookie
1. this is the bit that bugs me; while you should be authenticated, the Sales app seems to redirect you again to your Identity Server app for some reason, which it shouldn't do from my understanding

Another thing I find strange is that the extended logs you shared don't show that last `GET /Account/Login` request going to Identity Server.

What I would recommend is:

- verify through the Edge DevTools where the `POST /signin-oidc` request redirects to;
- try to find out somehow where the `GET /Account/Login` request after you log in comes from 

Sorry I'm not of huge help, here, I've never encountered this issue before. Hopefully someone on Stack Overflow will find something.

Cheers!

**Comment by dresdor** [comment]
Thank you for the response.

At the moment, both Edge and IE 11's developer tools are bugged on my
machine, so I am having issues trying to further investigate this.

I did open up the same page in chrome and matched the network traffic.
 The successful login from Chrome does not have the yellow highlighted
login call.

Because of this, I think that something is "wrong" with the cookie in IE
and Edge, probably they are using some form of stricter domain restrictions
on cookies (all of our sites share a common subdomain) than Chrome or
Firefox.

I've seen recommendation to set a value on the identity server cookies that
sets the domain at the parent domain level, but was not able to get it to
work (it caused chrome and firefox to also fail once done, so I'm sure I
didn't do something right).

-Marshall

**Comment by mderriey** [comment]
Hey, I'm now closing this issue since I haven't heard from you in a while.

Thanks,

**Comment by MitchDart** [comment]
Hi @dresdor and @mderriey. I am having exactly the same issue. Also using IdentityServer4. IE and Edge both give the error INET_E_DOWNLOAD_FAILURE. I would really appreciate it if you could explain how you fixed this problem? 

Thanks,

**Comment by dresdor** [comment]
We haven't been able to resolve it.  We've just added Edge and IE to the
list of browsers we do not support at this time.

Sorry I couldn't be of assistance.

-Marshall

**Comment by SiteStamp** [comment]
I know this is an older thread but I wanted to state what fixed our environment and IE 11 and Edge is working again.

Edge and IE 11 apparently do not like Http2, they accept it however if you notice on the network chain IE/Edge is doing a 302 to http/1.0 behind the scenes on its own.  Identity server does not like this and cuts the connection causing a redirect and re-auth loop.  To solve this I disabled Http2 on our gateway and it worked just fine after that.  

I am not a fan of this approach however our business requirements require support of IE 11 and Edge.

Thank you,
