### ISSUE TITLE
make a nuget package

### ISSUE THREAD

**Issue by bryanvam** [mderriey/aspnet-core-token-renewal#32]
it would be helpful to package this into nuget package so that we could drop this ready to use inside of our projects

**Comment by mderriey** [comment]
Hi,

Thanks for the suggestion.
However, I'm hesitant to do this because there's a really high chance IMO that every project will need subtle but important changes:

- what if you want to tweak when we try to refresh the access token?
- what if a different identity provider provides different claims?
- how would we store the client id and secret?
- what if you want to extend/modify what happens during the `ValidatePrincipal` event?

Another argument for not making a package is that this setup is usually done once at the start of the project and not often modified afterwards, so I don't see an issue with copying/pasting code from a previous project, while adapting to the current project's needs.

Cheers.
